// Media Query
export const SET_QUERY_TYPE = 'SET_QUERY_TYPE';

// Jackpot
export const SET_JACKPOT_DATA = 'SET_JACKPOT_DATA';

export const SET_WINNING_PRIZE = 'SET_WINNING_PRIZE';

export const SET_DISPLAY_WIN_PRIZE = 'SET_DISPLAY_WIN_PRIZE';
export const UPDATE_DISPLAY_WIN_PRIZE = 'UPDATE_DISPLAY_WIN_PRIZE';

export const REMOVE_WIN_PRIZE_FROM_LIST_AND_DISPLAY_DATA = 'REMOVE_WIN_PRIZE_FROM_LIST_AND_DISPLAY_DATA';

export const SHOW_TOAST = 'SHOW_TOAST';

export const SET_SERVICE_BELL = 'SET_SERVICE_BELL';
export const REMOVE_SERVICE_BELL_FROM_LIST = 'REMOVE_SERVICE_BELL_FROM_LIST';

// hand pay
export const SEND_HAND_PAY_REQUEST = 'SEND_HAND_PAY_REQUEST';
export const HAND_PAY_SUCCESS = 'HAND_PAY_SUCCESS';
export const HAND_PAY_FAIL = 'HAND_PAY_FAIL';
export const CLEAN_HAND_PAY_STATE = 'CLEAN_HAND_PAY_STATE';
